### PR TITLE
Cosmetic

### PR DESCRIPTION
**Pull request by alejandro-colomar**

### CODE REVIEW

**Comment by scolomar** [comment]
I am sorry but it is not possible. 
Two spaces is currently a de facto standard and using a different spacing pattern would make it really difficult to share or use code from other parties.

**Comment by alejandro-colomar** [comment]
> I am sorry but it is not possible.
> Two spaces is currently a de facto standard and using a different spacing pattern would make it really difficult to share or use code from other parties.

Code shouldn't be written to be easy to copy&paste.  Code should be written to be easy to read.

Editors are responsible for fixing tabs and spaces.  Usually fixing a file involves 3 or 4 mouse clicks.

**Comment by scolomar** [comment]
> Editors are responsible for fixing tabs and spaces. Usually fixing a file involves 3 or 4 mouse clicks.

It is not that easy. An error in the tabulation of a YAML file could potentially cause a catastrophic failure in production. I will not take that risk.

**Comment by alejandro-colomar** [comment]
> > Editors are responsible for fixing tabs and spaces. Usually fixing a file involves 3 or 4 mouse clicks.
> 
> It is not that easy. 

It is.  I've done it many times.
image

>An error in the tabulation of a YAML file could potentially cause a catastrophic failure in production. I will not take that risk.

1-  YAML is brain-damaged and does not support tabs.  So there is no tabulation.  I guess you mean indentation.

2- The reason for large indentation is exactly that one:  humans can easily see the indentation, and errors are more unlikely to happen.  With too small indentation humans can't detect the indentation, and these catastrophic errors happen.

**Pull request closed without merging**
